name: nvim-docs
on:
  push:
    branches:
      - master
    paths:
      - 'packages/nvim-esmodtree/**'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-mise-with-lua-deps
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate vim docs
        run: pnpm docgen
        working-directory: packages/nvim-esmodtree
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'chore(ci): auto-generate vimdoc'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          file_pattern: packages/nvim-esmodtree/doc/*
